name: opampsupervisor-image

on:
  push:
    branches:
      - main
    tags:
      - "cx-opampsupervisor/v[0-9]+.[0-9]+.[0-9]+*"
    paths-ignore:
      - "**/README.md"
  merge_group:
  pull_request:
    paths-ignore:
      - "**/README.md"

env:
  IMAGE_NAME: cgx.jfrog.io/coralogix-docker-images/cx-opampsupervisor
  # Make sure to exit early if cache segment download times out after 2 minutes.
  # We limit cache download as a whole to 5 minutes.
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2

# Do not cancel this workflow on main. See https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16616
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  linux-supervisor-tests:
    runs-on: ubuntu-24.04
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./.github/actions/setup-go-tools
        with:
          go-version: oldstable
          install-tools: "false"
      - name: Run opampsupervisor tests (non-e2e)
        run: |
          cd cmd/opampsupervisor
          go test -v ./...
      - run: ./.github/workflows/scripts/check-disk-space.sh

  supervisor-e2e-tests:
    runs-on: ubuntu-24.04
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./.github/actions/setup-go-tools
        with:
          go-version: oldstable
          install-tools: "false"
      - name: Generate otelcontribcol files
        run: make genotelcontribcol
      - name: Build Collector
        run: make otelcontribcol
      - name: Run opampsupervisor e2e tests
        run: |
          cd cmd/opampsupervisor
          go test -v --tags=e2e
      - run: ./.github/workflows/scripts/check-disk-space.sh

  build:
    needs: [linux-supervisor-tests, supervisor-e2e-tests]
    runs-on: ubuntu-24.04
    if: ${{ github.actor != 'dependabot[bot]' }}
    env:
      SHOULD_PUSH: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/cx-opampsupervisor/v') }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./.github/actions/setup-go-tools
        with:
          go-version: oldstable
          install-tools: "false"
      - name: Determine image tag
        id: metadata
        run: |
          if [[ "${SHOULD_PUSH}" == "true" ]]; then
            echo "image_tag=${GITHUB_REF_NAME#cx-opampsupervisor/}" >> "$GITHUB_OUTPUT"
          else
            echo "image_tag=local-${GITHUB_RUN_ID}" >> "$GITHUB_OUTPUT"
          fi
      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
      - name: Build linux binaries
        run: |
          GOOS=linux GOARCH=amd64 make opampsupervisor
          GOOS=linux GOARCH=arm64 make opampsupervisor
          cp bin/opampsupervisor_linux_amd64 cmd/opampsupervisor/opampsupervisor-linux-amd64
          cp bin/opampsupervisor_linux_arm64 cmd/opampsupervisor/opampsupervisor-linux-arm64
      - name: Login to JFrog
        if: env.SHOULD_PUSH == 'true'
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: cgx.jfrog.io
          username: ${{ secrets.JFROG_USER }}
          password: ${{ secrets.JFROG_PASSWORD }}
      - name: Build and optionally publish image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: cmd/opampsupervisor
          file: cmd/opampsupervisor/Dockerfile.release
          push: ${{ env.SHOULD_PUSH == 'true' }}
          tags: ${{ env.IMAGE_NAME }}:${{ steps.metadata.outputs.image_tag }}
          platforms: linux/amd64,linux/arm64
      - run: ./.github/workflows/scripts/check-disk-space.sh
